# Forcibly include specified modules at compile time
- module-name: '__main__'
  implicit-imports:
    - depends:
        - 'PySide6'
        - 'qtpy'
        - 'veusz'
        - 'numpy'
        - 'xarray'
        - 'astropy'
        - 'veusz'
        - 'veusz.plugins'  # Include plugins if used
        - 'veusz.helpers'

# Additional configuration for PySide6/Qt
- module-name: 'pyside6'
  implicit-imports:
    - depends:
        - 'PySide6.QtCore'
        - 'PySide6.QtGui'
        - 'PySide6.QtWidgets'
  data-files:
    - dirs:
        - 'plugins'
        - 'qml'
    - patterns:
        - '*.so'
        - '*.dll'
        - '*.dylib'

# numpy requires special handling
- module-name: 'numpy'
  implicit-imports:
    - depends:
        - 'numpy.core'
        - 'numpy.lib'
  # anti-bloat:
    # - no-auto-follow:
        # 'scipy': 'ignore'

# astropy configuration
- module-name: 'astropy'
  data-files:
    - dirs:
        - 'data'
    - patterns:
        - '*.cfg'
        - '*.yaml'
        

# veusz.nuitka-package.config.yml       
- module-name: 'veusz'
  data-files:
    - dirs:
        - 'data'  # Relative to veusz package
    - patterns:
        - '*.json'
        - '*.ui'
        - '*.icns'

# Custom Imports
# - module-name: 'your_module'
  # implicit-imports:
    # - depends:
        # - 'dynamically_loaded.module'